// Angular/welcome-app/src/app/greet/greet.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'sw-greet',
  templateUrl: './greet.component.html',
  styleUrls: ['./greet.component.css']
})
export class GreetComponent implements OnInit {

  greetingMessage: string;
  constructor() {
    this.greetingMessage = "";
  }

  handleGreet(userName: string) {
    let hrs = new Date().getHours();
    let time = hrs<12? "morning" : hrs<18? "afternoon" : "evening";
    this.greetingMessage = `Hello ${userName} , Good ${time}`;
  }

  ngOnInit(): void {
  }

}

<div>
    Enter name : <input type="text" value="Faisal" #txtUserName>
    <br>
    <input type="button" value="greet" (click) = "handleGreet(txtUserName.value)">
    {{greetingMessage}}
</div>

// React/welcome-app/src/Greet.js
import React, { useState } from "react";

export default () => {

    const [userName, setUserName] = useState("");

    const submitForm = (e) => {
        e.preventDefault();
        
        let hrs = new Date().getHours();
        let time = hrs<12? "morning" : "evening";
        const greetingMessage = `Hello ${userName}, Good ${time}`;

        console.log(greetingMessage);

    };

    return (
        <>
            <div id="container">
                <form action="" onSubmit={submitForm}>
                    <div>
                        <label htmlFor="username">Username</label>
                        <input
                            type="text"
                            name="username"
                            id="username"
                            value={userName}
                            onChange={(e) => setUserName(e.target.value)}
                        ></input>
                    </div>

                    <button type="submit">Login</button>
                </form>


            </div>
        </>
    );
};
